module.exports = {
  reactStrictMode: true,
  env: {
    NODE_ENV: process.env.NODE_ENV,
    NEXT_PUBLIC_SOLANA_NETWORK: process.env.NEXT_PUBLIC_SOLANA_NETWORK,
    NEXT_PUBLIC_SOLANA_RPC_HOST: process.env.NEXT_PUBLIC_SOLANA_RPC_HOST,
    NEXT_PUBLIC_CROSSMINT_API_URL: process.env.NEXT_PUBLIC_CROSSMINT_API_URL,
    NEXT_PUBLIC_JUPITER_API_URL: process.env.NEXT_PUBLIC_JUPITER_API_URL,
    NEXT_PUBLIC_HELIUS_API_URL: process.env.NEXT_PUBLIC_HELIUS_API_URL,
    NEXT_PUBLIC_CROSSMINT_API_KEY: process.env.NEXT_PUBLIC_CROSSMINT_API_KEY,
    NEXT_PUBLIC_JUPITER_API_KEY: process.env.NEXT_PUBLIC_JUPITER_API_KEY,
    NEXT_PUBLIC_HELIUS_API_KEY: process.env.NEXT_PUBLIC_HELIUS_API_KEY,
    NEXT_PUBLIC_FEATURE_AI: process.env.NEXT_PUBLIC_FEATURE_AI,
    NEXT_PUBLIC_FEATURE_NFT: process.env.NEXT_PUBLIC_FEATURE_NFT
  },
};
